### ISSUE TITLE
Find training set

### ISSUE THREAD

**Issue by AleksBekker** [Linalg-Class/create-dataset#1]
We need datasets of images that contain:
A) lots of people who look very different
B) different angles of those people

You could start at: https://github.com/blancaag/face-datasets

**Comment by AdrianS143** [comment]
https://drive.google.com/drive/folders/0BxYys69jI14kU0I1YUQyY1ZDRUE?resourcekey=0-01Pth1hq20K4kuGVkp3oBw&usp=sharing
